version: '3.3'

services:
  db1:
    #    image: mysql:5.7
    restart: always
    container_name: db1
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    ports:
      - 3306:3306
#    networks:
#      - mt-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=resu
      - MYSQL_DATABASE=KS

  app:
    container_name: app
    build:
      context: ./Docker
      dockerfile: app.Dockerfile
    ports:
      - 8080:8080
    links:
      - db1:db1
    depends_on:
        - db1
#    networks:
#      - mt-network
    environment:
      - JAVA_TOOL_OPTIONS=-Xms1024M -Xmx8192M

#networks:
#  mt-network:
#    driver: bridge